title: Maia Chess
baseurl: ""
url: "https://maiachess.com"

sass:
  sass_dir: assets/_sass

permalink: pretty

header_pages:
  - About
  - Blog
  - Papers
  - Play
  - Examples
  - Team
  - Contact

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.sh"
  - CNAME
