title: Maia Chess
baseurl: ""
url: "https://maiachess.com"

sass:
  sass_dir: assets/_sass

permalink: pretty

header_pages:
  - Play
  - Examples
  - Papers
  - About

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.sh"
  - CNAME
